# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Archiwalna Ortofotomapa
                                 A QGIS plugin
 Pozwala na podczytanie w QGIS archiwalnej ortofotomapy na podstawie usług geoportal.gov.pl
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-25
        copyright            : (C) 2020 by EnviroSolutions Sp. z o.o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
from datetime import datetime

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from .constants import OLDEST_ORTO_YEAR

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'archiwalna_ortofotomapa_dockwidget_base.ui'))


class ArchiwalnaOrtofotomapaDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""

        super().__init__(parent)
        # Set up the user interface from Designer.  
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.img_main.setContentsMargins(3, 3, 3, 3)
        
        # Store current year
        self.currentYear = datetime.now().year
        
        # Initialize slider min/max values
        self.timeSlider.setMinimum(OLDEST_ORTO_YEAR)
        self.timeSlider.setMaximum(self.currentYear)
        
        # Internal state for slider
        self.isSliderPressed = False
        
        # Set slider to current year by default
        self.setSliderToMaxYear()

    def setSliderToMaxYear(self):
        """Sets the slider to the maximum year (current year)."""
        self.currentYear = datetime.now().year
        self.timeSlider.setMaximum(self.currentYear)
        self.timeSlider.setSliderPosition(self.currentYear)
        self.timeLabel.setText(str(self.currentYear))

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
